project:
  type: website
  output-dir: docs
  
website:
  title: "IVY YEUNG"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/ivy-y/
      - icon: github
        href: https://github.com/i-vy-i/portfolio-website
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2025, Ivy Yeung"

format:
  html:
    theme: brite
    toc: true

editor: source

